### ISSUE TITLE
Unstable Connection

### ISSUE THREAD

**Issue by dozer1dave** [tmknight/docker-nordvpn#34]
Anyone else seeing a message "WARNING	Unstable connection detected"  followed by multiple connections with an uptime of 4:10.  I was seeing this with bubuntux too and was hopeful that the new client resolved...
  

########################
2023-02-09 02:21:38+0000 	INFO	Enabling connection to IPv4 network 192.168.1.0/24
2023-02-09 02:21:38+0000 	INFO	Startup complete
2023-02-09 02:21:38+0000 	INFO	Periodic VPN connection refresh is disabled
2023-02-09 02:25:48+0000 	WARNING	Unstable connection detected
########################

-
  
Status: Connected
Hostname: us10110.nordvpn.com
IP: 37.19.200.226
Country: United States
City: Dallas
Current technology: OPENVPN
Current protocol: UDP
Transfer: 258.62 KiB received, 94.87 KiB sent
Uptime: 4 minutes 10 seconds

**Comment by tmknight** [comment]
Right, as you saw/see this in other Nord implementations, that tells you it is a Nord issue and related to the server to which you are connected to having internet connectivity issues.  What you are seeing in the log is the result of the container checking for connection to the internet and it failing...after a period of time it reconnects.  I believe you are the one who connects to a specific server each time, so you're just going to get the same poor connectivity on each reconnect.  Not anything that can be fixed in this project.  You should contact Nord to get a new server assigned or however static IPs work.  Sorry.

**Comment by tmknight** [comment]
One other thing to consider is what [CHECK_CONNECTION_URL](https://github.com/tmknight/docker-nordvpn#:~:text=CHECK_CONNECTION_URL) you are using.  We default to google.com, however, if you've applied your own value, it needs to [pass these criteria](https://github.com/tmknight/docker-nordvpn/blob/923d3b345585584130bb146b691c66e1402af1ed/scripts/nord_watch#L33)
